service: lambda-test

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-west-2

functions:
  hello:
    handler: greetings.hello
    events:
      - http:
          path: hello
          method: GET
